<a href="https://colab.research.google.com/github/LuigiAjello/learning_numpy/blob/main/numpy_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import sys

In [41]:
a=np.array([1,2,3],dtype= "int16") #como sabemos que os dados vao ser todos inteiros podemos indicar seu tipo e como sabemos que vao ser pequenos podemos indicar quantos bites usar para nao precisar usar mais que iremos 16bits(2bytes [1 byte = 8 bits])
print(a)

[1 2 3]


In [ ]:
b =np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])#aqui nao especificamos nada
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#Get Dimesion
print(a.ndim)

print(b.ndim)

1
2


In [ ]:
#Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# Get Type

print(a.dtype)
print(b.dtype)

int16
float64


In [ ]:
#Get Size (tamanho dos BYTES  [nao necessariamente sao os de fatos utilizados posso nao especificar 16 e usar mais que o necessario ])
print(a.itemsize )
print(b.itemsize)

2
8


In [ ]:
#get total size (tamanho dos itens)
print(a.size)
print(b.size)

3
6


# Accessing/changing specific elements, rows, columns, etc


In [64]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
# get specific element [roww, column] (comeca com 0 igual listas) 0 pega o primeiro [0,0]
#quero pegar o 13 entao esta na segunda  fileira(1)  coluna (5)
a[1,5]

13

In [55]:
#get specific row
print(a[1,:])
print(a[1, 2 : 4]) # pega no intervalo entre a segunda (1) e a 5 (4) e nao inclui elas

[ 8  9 10 11 12 13 14]
[10 11]


In [59]:
#get specific column (todos tem a mesma estrutura de [roww,column] e de [ : ])
a[:,2]

array([ 3, 10])

In [62]:
# get little more "fancy" [row,startindex : endingindex : stepsize]
print(a[0,1:6:1])
print(a[0,1:6:2]) # vai de dois em dois pois tem o 2 de stepsize

[2 3 4 5 6]
[2 4 6]


In [1]:
#changing

a[1,5] = 20
print(a)

SyntaxError: invalid decimal literal (<ipython-input-1-d0ed2f5c1b8b>, line 4)

In [ ]:
#ex 3D

In [68]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [75]:
#get specific element (work outside in)\
print(b[0,1,1])
print(",,,,,,,")
print(b[:, 1,:])
print(",,,,,,,")
print(b[0,1,:])
print(",,,,,,,")
print(b[:,1,1])

4
,,,,,,,
[[3 4]
 [7 8]]
,,,,,,,
[3 4]
,,,,,,,
[4 8]


In [76]:
#replace
b[:, 1,:]= [[9, 9], [8, 8]]
print(b)


[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
